const mongoose = require('mongoose');

// Connect to MongoDB
mongoose.connect('MongoDB-Link');

// Define schemas
const AdminSchema = new mongoose.Schema({
    // Schema definition here
    username: String,
    password: String
});

const UserSchema = new mongoose.Schema({
    // Schema definition here
    username: String,
    password: String,
    purchasedCourses: [{    
        type: mongoose.Schema.Types.ObjectId,    //refer below
        ref: 'Course'
    }]
});

const CourseSchema = new mongoose.Schema({
    // Schema definition here
    title: String,
    description: String, 
    imageLink: String, 
    price: Number
});

const Admin = mongoose.model('Admin', AdminSchema);
const User = mongoose.model('User', UserSchema);
const Course = mongoose.model('Course', CourseSchema);

module.exports = {
    Admin,
    User,
    Course
}


// type: mongoose.Schema.Types.ObjectId : This specifies the type of data that each element in the 
//     purchasedCourses array should be. In this case, it's an ObjectId, which is the unique identifier 
//     generated by MongoDB for each document in a collection